"""create slo and plo tables

Revision ID: 65b3baddaf16
Revises: f420e097b990
Create Date: 2025-08-19 20:20:01.845415

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '65b3baddaf16'
down_revision: Union[str, Sequence[str], None] = 'f420e097b990'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('plo',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('university_code', sa.String(), nullable=False),
    sa.Column('specialty_code', sa.String(), nullable=False),
    sa.Column('plo_code', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['specialty_code'], ['specialties.specialty_code'], ),
    sa.ForeignKeyConstraint(['university_code'], ['universities.university_code'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('plo_code')
    )
    op.create_index(op.f('ix_plo_id'), 'plo', ['id'], unique=False)
    op.create_table('plo_translations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('plo_code', sa.String(), nullable=False),
    sa.Column('language_code', sa.CHAR(length=2), nullable=False),
    sa.Column('plo_content', sa.Text(), nullable=False),
    sa.ForeignKeyConstraint(['plo_code'], ['plo.plo_code'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('plo_code', 'language_code')
    )
    op.create_index(op.f('ix_plo_translations_id'), 'plo_translations', ['id'], unique=False)
    op.create_table('slo',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('university_code', sa.String(), nullable=False),
    sa.Column('specialty_code', sa.String(), nullable=False),
    sa.Column('slo_code', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['specialty_code'], ['specialties.specialty_code'], ),
    sa.ForeignKeyConstraint(['university_code'], ['universities.university_code'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('slo_code')
    )
    op.create_index(op.f('ix_slo_id'), 'slo', ['id'], unique=False)
    op.create_table('slo_translations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('slo_code', sa.String(), nullable=False),
    sa.Column('language_code', sa.CHAR(length=2), nullable=False),
    sa.Column('slo_content', sa.Text(), nullable=False),
    sa.ForeignKeyConstraint(['slo_code'], ['slo.slo_code'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('slo_code', 'language_code')
    )
    op.create_index(op.f('ix_slo_translations_id'), 'slo_translations', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_slo_translations_id'), table_name='slo_translations')
    op.drop_table('slo_translations')
    op.drop_index(op.f('ix_slo_id'), table_name='slo')
    op.drop_table('slo')
    op.drop_index(op.f('ix_plo_translations_id'), table_name='plo_translations')
    op.drop_table('plo_translations')
    op.drop_index(op.f('ix_plo_id'), table_name='plo')
    op.drop_table('plo')
    # ### end Alembic commands ###